spring.application.name=pictweet
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/pictweet_java_error
spring.datasource.username=kiri
spring.datasource.password=taisei0323
spring.flyway.baselineOnMigrate=true

server.error.include-stacktrace=always